Update dsecret

diff --git a/dsecret b/dsecret
--- a/dsecret
+++ b/dsecret
@@ -57,35 +57,37 @@ trim() {
 
 decrypt() {
    local INPUT_FILE="$1"
-   [ ${INPUT_FILE: -2} == ".e" ] || return
+   [ ${INPUT_FILE: -2} == ".e" ] || return 0
    local OUTPUT_FILE=${INPUT_FILE::-2}  # drop last two characters.
 
    [ ! -e ${OUTPUT_FILE} ] || die "Output file already exists: ${OUTPUT_FILE}"
    [ ! -z $PASSPHRASE ] || die "Passphrase undefined."
 
-   echo "Decrypting ${INPUT_FILE}"
+   echo "Decrypting $(basename ${OUTPUT_FILE})"
 
    output=$(gpg --yes --batch --passphrase=${PASSPHRASE} -o ${OUTPUT_FILE} -d ${INPUT_FILE}  2>&1)
 
    [ $? -eq 0 ] || die "Decryption failed: $output"
    unlink "${INPUT_FILE}"
+   [ $? -eq 0 ] || die "Unlink failed: ${INPUT_FILE}"
 }
 
 encrypt() {
    local INPUT_FILE="$1"
-   [ ${INPUT_FILE: -2} != ".e" ] || return
+   [ ${INPUT_FILE: -2} != ".e" ] || return 0
    local OUTPUT_FILE="${INPUT_FILE}.e"
 
    [ ! -e ${OUTPUT_FILE} ] || die "Output file already exists: ${OUTPUT_FILE}" #unlink "${OUTPUT_FILE}"
    [ ! -z $PASSPHRASE ] || die "Passphrase undefined."
 
-   echo "Encrypting ${INPUT_FILE}" #to ${OUTPUT_FILE}"
+   echo "Encrypting $(basename ${OUTPUT_FILE})" #to ${OUTPUT_FILE}"
 
    output=$(gpg --yes --batch --armor --symmetric --cipher-algo AES256 \
       --passphrase=${PASSPHRASE} -o ${OUTPUT_FILE} -c ${INPUT_FILE} 2>&1)
 
    [ $? -eq 0 ] || die "Encryption failed: $output"
    unlink "${INPUT_FILE}"
+   [ $? -eq 0 ] || die "Unlink failed: ${INPUT_FILE}"
 }
 
 findup () {
@@ -117,7 +119,7 @@ get_passphrase() {
 
 
 dofile() {
-   if [ $MODE == "e" ]; then
+   if [[ "$DOENCRYPT" == true ]]; then
       encrypt $1
    else
       decrypt $1
@@ -125,10 +127,11 @@ dofile() {
 }
 
 walk() {
-   echo "Checking $1"
+   #echo "Checking $1"
    if [ -f "$1" ]; then
       dofile "$1"
    elif [ -d "$1" ]; then
+      echo "Searching $1"
       # If the entry is a file do some operations
       for entry in "$1"/*; do [[ -f "$entry" ]] && dofile "$entry"; done
       # If the entry is a directory call walk() == create recursion
@@ -154,20 +157,25 @@ show_help() {
 
 
 #------------------------
-
 if [ "$#" -eq 1 ]; then
    INPUT_FILE=$(realpath "$1")
    [[ ! -z "${INPUT_FILE}" && -f "${INPUT_FILE}" ]] || show_help
-   MODE="e"
-   if [[ ${INPUT_FILE: -2} != ".e" ]]; then 
-      MODE="d"
+   DOENCRYPT=false   # false.
+   if [[ ${INPUT_FILE: -2} != ".e" ]]; then
+      DOENCRYPT=true
    fi
 else
    [ "$#" -eq 2 ] || show_help
-   MODE="$1"
-   if [[ $MODE != "e" && $MODE != "d" ]]; then
-      show_help
-   fi
+   case $1 in
+      e)
+         DOENCRYPT=true 
+         ;;
+      d)
+         DOENCRYPT=false
+         ;;
+      *)
+         show_help
+   esac
    INPUT_FILE=$(realpath "$2")
    [ -d "${INPUT_FILE}" ] || show_help
 fi
