Update dsecret

diff --git a/dsecret b/dsecret
--- a/dsecret
+++ b/dsecret
@@ -103,13 +103,13 @@ get_passphrase() {
    DIR="$1"
    [ -d "$DIR" ] || DIR=$(dirname "$1")
 
-   PASSPHRASE_ENV_FILE="$(findup $DIR "dsecret.cfg")"
+   PASSPHRASE_ENV_FILE="$(findup $DIR ".dsecret.cfg")"
 
-   [ -f "${PASSPHRASE_ENV_FILE}" ] || die "FATAL! Couldn't find dsecret.cfg in parent directories."
+   [ -f "${PASSPHRASE_ENV_FILE}" ] || die "FATAL! Couldn't find .dsecret.cfg in parent directories."
 
    source ${PASSPHRASE_ENV_FILE}
 
-   [ ! -z ${PASSPHRASE_ENV:-} ] || die "The dsecret.cfg file did not define PASSPHRASE_ENV"
+   [ ! -z ${PASSPHRASE_ENV:-} ] || die "The .dsecret.cfg file did not define PASSPHRASE_ENV"
    [ ! -z "${!PASSPHRASE_ENV:-}" ] || die "FATAL! Environment variable not set: DEVOPS_PASSPHRASE_LOGAN"
    PASSPHRASE=$(trim "${!PASSPHRASE_ENV}")
 }
@@ -138,26 +138,21 @@ walk() {
 }
 
 show_help() {
-   echo "dsecret - simple secret management"
+   echo "dsecret - simple secret management, AES-256 encryption."
+   echo " "
+   echo "dsecret relies on a .dsecret.cfg file being in the upwards path,"
+   echo "which defines the environment variable to retrieve the passphrase."
+   echo "It only decrypts files with extension .e, and will encrypt anything else."
    echo " "
    echo "usage: "
    echo " dsecret FILENAME           Encrypt/Decrypt single file"
    echo " dsecret {e|d} DIRECTORY    Recursively Encrypt/Decrypt directory"
-   echo " dsecret install            Symlink to /usr/local/bin"
    echo " "
    exit 0
 }
 
 
 #------------------------
-
-if [[ "$#" -eq 1 && "$1" == "install" ]]; then
-   [[ $EUID -eq 0 ]] || die "Install must be run as root" 
-   DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-   ln -s "$DIR/dsecret" /usr/local/bin/dsecret
-   chmod a+rx /usr/local/bin/dsecret
-   exit 0;
-fi
 
 if [ "$#" -eq 1 ]; then
    INPUT_FILE=$(realpath "$1")
